Чукарев Михаил 6311
itsecd/ptm-5 pull request #24
Opened 2023-12-12 17:10 UTC by Mishachuu

Добавил пару тестов для модульного тестирования игры SNAKE (🐍) WATER (💧) GUN (🔫)

2023-12-12 17:57 UTC, Mishachuu commented
я сдаюсь...

2023-12-13 10:29 UTC, alxmcs requested changes
В `requirements.txt` 100+ пакетов, они явно не нужны в таком количестве в этом проекте. У тебя единственная виртуальная среда на все твои проекты на питоне?

2023-12-13 10:35 UTC, Mishachuu commented
С пакетами то понятно, но не в них дело

2023-12-13 10:38 UTC, alxmcs requested changes
Так разберись с ними сначала

2023-12-13 11:07 UTC, alxmcs requested changes

2023-12-13 11:07 UTC, alxmcs commented on requirements.txt
Все, что тебе понадобится из этого, это
```py
asgiref==3.7.2
emoji==2.9.0
simple-colors==0.1.5
typing_extensions==4.9.0

```

2023-12-13 11:07 UTC, alxmcs commented on game.py
> +    computer_choice, user_choice, replay = "", "", ""  # Emptying strings at the beginning of the game
А тесты у тебя не работают в CI потому что тут нет `if ___name__ == "__main__":` , так что при запуске тестов запускается и игра, которая ожидает ввода до тех пор, пока виртуалка не погасится по таймауту

2023-12-13 11:07 UTC, alxmcs commented on test_game.py
> +from unittest.mock import patch
Мы вроде договаривались, что используем только `pytest`

2023-12-13 11:08 UTC, Mishachuu commented on game.py
> +    computer_choice, user_choice, replay = "", "", ""  # Emptying strings at the beginning of the game
Main был в прошлой версии, но точно так же тесты висели

2023-12-13 20:29 UTC, Mishachuu commented
Возможно прохождение тестов затруднено глоб. переменными

2023-12-14 09:01 UTC, alxmcs requested changes

2023-12-14 09:01 UTC, alxmcs commented on test_game.py
Обожаю делать лабы за студентов (нет)
Проблема действительно в глобальных переменных - потому что ты не те глобальные переменные в тесты поместил

```py
import unittest
from unittest.mock import patch
import game


class TestGame(unittest.TestCase):

    @patch('game.computer_choice', 'Gun')
    @patch('game.user_choice', 'g')
    def test_result_draw_gun(self):
        """Проверка, что очки не изменились, если оба выбрали пистолет
        """
        game.results()
        self.assertEqual(game.user_points, 0)
        self.assertEqual(game.computer_points, 0)

    @patch('game.computer_choice', 'Snake')
    @patch('game.user_choice', 'w')
    def test_snake_drinks_water(self):
        """Проверка, что очки  изменились, если компьютер выбрал змею, а пользователь воду
        """
        game.results()
        self.assertEqual(game.user_points, 0)
        self.assertEqual(game.computer_points, 1)
```

Собственно, твое мучение с тестированием наглядно демонстрирует, почему автору игры надо сломать пальцы.

2023-12-14 09:01 UTC, alxmcs commented on test_game.py
> +from unittest.mock import patch
Напомню, что перенос тестов на pytest все еще актуален

2023-12-15 08:41 UTC, alxmcs requested changes
1. Я не зря импортировал модуль целиком в примере своего кода, а не отдельные его компоненты.
2. Контекст у параметризованного теста остается один и тот же на все запуски из-за того, что приходится тащить весь модуль целиком:
```py
import pytest
import game

@pytest.mark.parametrize("comp_choice, user_input, exp_user_points, exp_comp_points", [
    ('Snake', 's', 0, 0), 
    ('Water', 'w', 0, 0),
    ('Gun', 'g', 0, 0),   
    ('Snake', 'g', 1, 0),
    ('Water', 's', 2, 0),
    ('Gun', 'w', 3, 0),
    ('Snake', 'w', 3, 1),
    ('Water', 'g', 3, 2),
    ('Gun', 's', 3, 3),
])
def test_game_results(comp_choice, user_input, exp_user_points, exp_comp_points):
    """тестирование различных сценариев игры и проверка очков

    Args:
        comp_choice (_type_): выбор компьютера
        user_input (_type_): выбор пользователя
        exp_user_points (_type_): ожидаемое количество очков пользователя
        exp_comp_points (_type_): ожидаемое количество очков компьютера
    """

    game.results(comp_choice, user_input)
    assert game.user_points == exp_user_points
    assert game.computer_points == exp_comp_points
```
3. Не хочу расстраивать, но
![image](https://github.com/itsecd/ptm-5/assets/70561974/24897373-b23a-418c-b410-19a2dc34bd8f)
И, в целом, не буду, тестировать в этом спидозном коде особо нечего. Да и морально-нравственных страданий ты ощутил достаточное количество, так что просто заставь текущие тесты работать.

2023-12-21 06:56 UTC, alxmcs approved these changes
Зачтено

2023-12-21 06:58 UTC, closed without merging