Лабораторная работа 5 Чугунов Владислав 6311-100503D
itsecd/ptm-5 pull request #34
Opened 2023-12-16 09:19 UTC by Colnuwko

Работа посвящена юнит тестам

2023-12-16 09:44 UTC, alxmcs requested changes
Служебные файлы IDE в репозиторий добавил, а requirements.txt - нет

2023-12-17 18:15 UTC, Colnuwko commented
Искренне надеюсь что вы не получается в столь поздний час уведы на почту))
Тут проверка тестов не проходит, сначала писала ошибку невозможности установить пакеты, я исправил requirement, однако это не особо помогло.
Вот красивая картинка :)
![image](https://github.com/itsecd/ptm-5/assets/107910988/e6017586-4033-46a4-8dbe-dd12f053de8e)

2023-12-18 05:22 UTC, alxmcs requested changes
Контейнер для CI имеет крайне ограниченное количество оперативной памяти и не вывез твои тесты:
![image](https://github.com/itsecd/ptm-5/assets/70561974/a3ffd0f6-7d19-46c6-8a78-323bb4554830)

2023-12-18 05:22 UTC, alxmcs commented on test_my_app.py
> +        app.button_start_click()
Это крайне неудачный тест, ведь что чтобы он завершился, нужно нажать кнопку в появляющемся окне. Мы тут автоматизируем тестирование. В реальном проекте никому не надо сидеть и ловить момент, когда пора будет нажать на кнопку, чтобы юнит-тесты завершились.

В эту лабораторную притащен автоматизированный CI, чтобы смоделировать относительно реалистичную ситуацию. И контейнер с CI просто отвалится по таймауту, потому что не умеет нажимать на кнопки. И ему и не надо уметь, потому что тесты должны быть полностью автоматизированные.

2023-12-18 05:22 UTC, alxmcs commented on test_my_app.py
> +    assert graph.show_plt(cores, times)
Здесь аналогичная ситуация - вываливается окно с графиком, требующее закрытия

2023-12-18 05:22 UTC, alxmcs commented on test_my_app.py
> +        read_settings.read_json("20")
Декоратор `xfail`  - ~~игрушка дьявола ежжи~~ актуален только для крайне узкого набора ситуаций - когда имеется неимплементированный функционал (который в рамках релиза имплементирован не будет), когда имеется известный баг (и в рамках релиза он исправлен не будет) и т.д.

Не стоит с ним извращаться там, где его использование не требуется.

2023-12-18 05:22 UTC, alxmcs commented on test_my_app.py
> +     можно хоть 1000 потоков запустить, все упрется во время выполнения """
Очень радостно видеть, что тебя догнало осознание того, что число ядер != числу потоков исполнения

2023-12-22 14:52 UTC, Colnuwko commented on test_my_app.py
> +    assert alg_luhn.alg_luhn(numbers)
Исправил

2023-12-22 14:52 UTC, Colnuwko commented on test_my_app.py
> +from IPython.external.qt_for_kernel import QtCore
Исправил

2023-12-22 14:53 UTC, Colnuwko commented on test_my_app.py
> +        app.button_start_click()
Исправил

2023-12-22 14:53 UTC, Colnuwko commented on test_my_app.py
> +    assert graph.show_plt(cores, times)
исправил

2023-12-22 14:53 UTC, Colnuwko commented on test_my_app.py
> +        read_settings.read_json("20")
удалил, добавлял его потому что хотел посмотреть как это работает

2023-12-22 14:53 UTC, Colnuwko commented on test_my_app.py
> +     можно хоть 1000 потоков запустить, все упрется во время выполнения """
:)

2023-12-22 15:06 UTC, Colnuwko commented
Уменьшение тестов ситуацию не исправило,... Ну.... может оно и к лучшему? :)

2023-12-23 07:12 UTC, alxmcs approved these changes
Ладно, думаю, это можно зачесть
CI твои тесты не вывез, но я их позапускал сам

2023-12-23 07:53 UTC, closed without merging