Солдатова К. 6312-100503D
itsecd/ptm-5 pull request #42
Opened 2023-12-19 18:56 UTC by KsSoldatova

2023-12-20 07:21 UTC, alxmcs requested changes
Я эти юнит-тесты уже видел в #30, они там идентичны вплоть до названий методов и переменных в них.
Добавь к этим тестам несколько написанных тобой собственноручно.

2023-12-21 09:03 UTC, KsSoldatova commented
добавила тесты

2023-12-21 09:16 UTC, alxmcs requested changes

2023-12-21 11:58 UTC, KsSoldatova commented
добавила другой тест

2023-12-21 13:01 UTC, alxmcs approved these changes
Зачтено

2023-12-21 13:01 UTC, closed without merging