Нестеренко Андрей 6312 лаб 5
itsecd/ptm-5 pull request #8
Opened 2023-12-05 11:35 UTC by MagGoldi

Так как чат гпт клепанул крайне годный кодик в прошлой лабораторной работе(main.py), было принято решения использовать его для юнит тестов(test_unit.py)

2023-12-06 07:15 UTC, MagGoldi commented
Тут так получилось, что каким то неведомым образом, что я соединил ветки с #5 Панкеевом Глебом, лабы мы делали отдельно друг от друга, набедокурил конкретно, виноват🥴

2023-12-07 15:13 UTC, alxmcs commented on .vscode/settings.json
Файл IDE убрать

2023-12-07 15:15 UTC, alxmcs commented on requirements
Почему пусто?

2023-12-07 15:22 UTC, alxmcs commented on test_unit.py
> +    store.read_from_csv(filename)
И в чем практическая польза этих тестов? в них ассертов нет

2023-12-07 15:24 UTC, alxmcs commented on test_unit.py
> +    pytest.main(["-v", "-color=yes"])
Это излишне

2023-12-07 15:28 UTC, alxmcs commented on nonexistent_file.csv
` > nonexistent_file.csv`
` > exists`

![image](https://github.com/itsecd/ptm-5/assets/70561974/55ae0997-bec4-4885-909d-337d51f23dcf)

2023-12-12 17:46 UTC, MagGoldi commented on .gitignore
> +>>>>>>> 35cc3e65f15615821481f604d6a6ac49e9500b1d
я все красиво сделал

2023-12-12 17:47 UTC, MagGoldi commented on .github/workflows/requirements.txt
а потому что по другому гитхаб экшон не проходит проверку

2023-12-12 17:47 UTC, MagGoldi commented on requirements
Binary file not shown.

2023-12-13 10:14 UTC, alxmcs requested changes

2023-12-13 10:14 UTC, alxmcs commented on test_unit.py
> +@pytest.mark.parametrize("filename", ["test_product.csv"])
Бессмысленно параметризовывать тест и передавать в него только один набор значений. Проще и быстрее написать непараметризованный тест в таком случае.

Либо убрать параметризацию, либо пополнить наборы параметров

2023-12-13 10:14 UTC, alxmcs commented on test_unit.py
> +@pytest.mark.parametrize("filename", ["test_product.csv"])
Аналогично

2023-12-14 08:24 UTC, alxmcs requested changes
Теперь юнит-тесты не соответствуют условиям сдачи - нужно не менее 2 "не примитивных" теста
Лучше было докидать наборов параметров в параметризованные тесты))))))

2023-12-14 08:24 UTC, alxmcs commented on test_unit.py
> +    return Product()
Фикстура не используется

2023-12-14 08:24 UTC, alxmcs commented on test_unit.py
> +    :store: ProductStore
Но тут нет никакого `store`

2023-12-15 09:48 UTC, alxmcs approved these changes
<img src ="https://media.tenor.com/eXkvpaKHqUoAAAAM/stupid-idiot-cat-dancing.gif" />

2023-12-15 09:48 UTC, closed without merging

2023-12-15 09:51 UTC, MagGoldi commented
убрать параметризацию 
![image](https://github.com/itsecd/ptm-5/assets/105880317/c1925cb7-d190-42dc-a8fd-ea64e18ba54a)